# NUMPY ASSIGNMENT II

In [2]:
import numpy as np

In [9]:
# Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10
vector = np.random.randint(0, 11, size=5)
vector

array([6, 7, 4, 0, 2])

In [10]:
# Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values​​except the first and last
vector = np.arange(15, 56)
vector[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [14]:
# Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array.
# creating a 3 by 3 array
arry = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
arry

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
# Calculating the cumulative sum over rows for each column
rows = np.cumsum(arry, axis=0)
rows

array([[ 2,  4,  6],
       [10, 14, 18],
       [24, 30, 36]], dtype=int32)

In [18]:
# Calculating the cumulative sum over columns for each column
cols = np.cumsum(arry, axis=1)
cols

array([[ 2,  6, 12],
       [ 8, 18, 30],
       [14, 30, 48]], dtype=int32)

In [20]:
# Write a NumPy program to compute the multiplication of two given matrices. 
# creating the matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 4], [6, 8]])


In [21]:
matrix1

array([[1, 2],
       [3, 4]])

In [22]:
matrix2

array([[2, 4],
       [6, 8]])

In [23]:
# multipling the two matrices
result = np.dot(matrix1, matrix2)
result

array([[14, 20],
       [30, 44]])